--------------------------------------------------------------------------------
-- nco.vhd -- 40-bit phase-accumulator numerically-controlled oscillator
--
-- Phase 4 (orchestrator plan section 8; docs/spec.md section 8).
--
-- WHAT THIS BLOCK DOES
-- --------------------
-- A free-running phase accumulator: on every rising clock edge the accumulator
-- advances by `increment` (mod 2**ACCUMULATOR_BITS).  The top accumulator bit
-- is brought straight out as rf_out, giving a continuous-phase 1-bit square
-- wave -- no sine lookup table in v1 (plan section 8: "Do not use a sine
-- lookup table initially.  The output will be a 1-bit square wave."; plan
-- section 18: "The GPIO is the digital carrier.  Removing harmonics is the
-- job of external hardware.").
--
--   phase_accumulator
--           |
--           v
--   phase + phase_increment
--           |
--           v
--        MSB  ->  rf_out
--
-- FREQUENCY LAW
-- -------------
-- For an increment I and clock f_clk the accumulator advances I/2**40 of a
-- full cycle per clock, so the output frequency is
--
--     f_out = I * f_clk / 2**40.
--
-- The frequency resolution is therefore
--
--     f_clk / 2**40 = 12e6 / 2**40 ~= 1.0914e-5 Hz   (at 12 MHz)
--
-- (docs/spec.md section 8: "frequency_resolution = calibrated_clock / 2^40",
-- "12e6/2^40 ~ 1.0914e-5 Hz"), which is far finer than the 1.46484375 Hz
-- WSPR tone spacing (docs/spec.md section 6) -- hundreds of thousands of
-- LSBs of margin.
--
-- Increments are generated by the provenance tool tools/calculate_nco.py
-- (docs/spec.md sections 5/8/9; plan sections 8/9); this RTL contains no
-- frequency constant and no floating-point arithmetic (plan section 9:
-- "Avoid floating-point arithmetic in RTL").
--
-- SAMPLED-OUTPUT LIMIT (documented honestly)
-- ------------------------------------------
-- rf_out is sampled at f_clk, so the highest fundamental it can represent is
-- the Nyquist frequency f_clk/2 (6 MHz at 12 MHz).  For I <= 2**39 the law
-- above holds exactly; for I > 2**39 the 1-bit MSB output folds and the
-- observable fundamental is (2**40 - I) * f_clk / 2**40.  The default 30 m RF
-- carrier (10.14 MHz, docs/spec.md section 9) is ABOVE 6 MHz, so at the
-- nominal 12 MHz clock it is not directly observable from rf_out; see
-- sim/tb_nco.vhd.  This block deliberately implements only the frozen
-- spec/plan architecture and leaves any harmonic/filtering decision to the
-- RF/integration phases.
--
-- RESET
-- -----
-- Synchronous, active high.  On reset the accumulator is cleared, so rf_out
-- is '0' (RF off) -- consistent with plan section 31: a reset during TX must
-- silence the output.
--
-- VHDL-93 ONLY (IEEE Std 1076-1993): explicit sensitivity list, no
-- process(all), no VHDL-2008 constructs.  Analyse with --std=93.
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity nco is
  generic (
    -- Phase-accumulator width.  Frozen at 40 bits (docs/spec.md section 8;
    -- plan section 8: "Use a 40-bit accumulator initially").  It is a generic
    -- so testbenches can exercise narrower/wider accumulators, but the
    -- product default and the increment tool both use 40.
    ACCUMULATOR_BITS : positive := 40
  );
  port (
    clk : in std_logic;   -- FPGA clock (nominal 12 MHz onboard oscillator)
    rst : in std_logic;   -- synchronous reset, active high

    -- Phase increment per clock, ACCUMULATOR_BITS wide, unsigned.
    -- rf_out frequency = increment * clk_hz / 2**ACCUMULATOR_BITS.
    increment : in std_logic_vector(ACCUMULATOR_BITS - 1 downto 0);

    -- 1-bit continuous-phase carrier (MSB of the phase accumulator).
    rf_out : out std_logic
  );
end entity nco;

architecture rtl of nco is

  ----------------------------------------------------------------------------
  -- Named constants (no hidden magic numbers -- plan section 6, AGENTS.md 7)
  ----------------------------------------------------------------------------

  -- Nominal FPGA clock.  Frozen: docs/spec.md section 8 (NOMINAL_CLOCK_HZ =
  -- 12000000, 12 MHz).  Provenance: iCEBreaker onboard 12 MHz oscillator
  -- shared with the FT2232H (plan section 3.1; AGENTS.md section 2.7).  The
  -- measured/calibrated clock is supplied to the system by clock_calibration;
  -- the increment itself is computed off-chip/at build time by
  -- tools/calculate_nco.py, so no clock constant is needed in the datapath.
  constant NOMINAL_CLOCK_HZ : positive := 12_000_000;

  ----------------------------------------------------------------------------
  -- Phase state
  ----------------------------------------------------------------------------
  -- The accumulator is the only state.  It is cleared so rf_out starts at '0'
  -- (RF off) after configuration, and clears on reset.
  signal phase_acc : unsigned(ACCUMULATOR_BITS - 1 downto 0) := (others => '0');

begin

  ----------------------------------------------------------------------------
  -- Phase accumulator.  One add per clock; the modulus is implicit in the
  -- width of the unsigned (2**ACCUMULATOR_BITS wraps naturally).
  ----------------------------------------------------------------------------
  p_accumulate : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        phase_acc <= (others => '0');
      else
        phase_acc <= phase_acc + unsigned(increment);
      end if;
    end if;
  end process p_accumulate;

  ----------------------------------------------------------------------------
  -- 1-bit carrier: the MSB is the sign of the accumulated phase, giving a
  -- continuous-phase square wave.  High while phase is in [2**(N-1), 2**N).
  ----------------------------------------------------------------------------
  rf_out <= phase_acc(ACCUMULATOR_BITS - 1);

end architecture rtl;
