--------------------------------------------------------------------------------
-- nco.vhd -- 40-bit phase-accumulator numerically-controlled oscillator
--
-- Phase 4 (orchestrator plan section 8; docs/spec.md section 8).
--
-- WHAT THIS BLOCK DOES
-- --------------------
-- A free-running phase accumulator: on every rising clock edge the accumulator
-- advances by `increment` (mod 2**ACCUMULATOR_BITS).  The top accumulator bit
-- is brought straight out as rf_out, giving a continuous-phase 1-bit square
-- wave -- no sine lookup table in v1 (plan section 8: "Do not use a sine
-- lookup table initially.  The output will be a 1-bit square wave."; plan
-- section 18: "The GPIO is the digital carrier.  Removing harmonics is the
-- job of external hardware.").
--
--   phase_accumulator
--           |
--           v
--   phase + phase_increment
--           |
--           v
--        MSB  ->  rf_out
--
-- FREQUENCY LAW
-- -------------
-- For an increment I and clock f_clk the accumulator advances I/2**40 of a
-- full cycle per clock, so the output frequency is
--
--     f_out = I * f_clk / 2**40.
--
-- The frequency resolution is therefore
--
--     f_clk / 2**40 = 12e6 / 2**40 ~= 1.0914e-5 Hz   (at 12 MHz)
--
-- (docs/spec.md section 8: "frequency_resolution = calibrated_clock / 2^40",
-- "12e6/2^40 ~ 1.0914e-5 Hz"), which is far finer than the 1.46484375 Hz
-- WSPR tone spacing (docs/spec.md section 6) -- a margin of about 134,000
-- LSBs (1.46484375 / 1.0914e-5; student review fixed an inflated phrasing).
-- The tone spacing itself is 12000/8192 Hz: one WSPR symbol lasts
-- 8192/12000 s (docs/protocol.md).
--
-- Increments are generated by the provenance tool tools/calculate_nco.py
-- (docs/spec.md sections 5/8/9; plan sections 8/9); this RTL contains no
-- frequency constant and no floating-point arithmetic (plan section 9:
-- "Avoid floating-point arithmetic in RTL").  At runtime the MODULATOR drives
-- `increment`, changing it once per WSPR symbol (4-FSK); this block is
-- deliberately modulation-agnostic.
--
-- SAMPLED-OUTPUT LIMIT (documented honestly)
-- ------------------------------------------
-- rf_out is sampled at f_clk, so the highest fundamental it can represent is
-- the Nyquist frequency f_clk/2 (6 MHz at 12 MHz).  For I <= 2**39 the law
-- above holds exactly; for I > 2**39 the 1-bit MSB output folds.  Mechanism
-- (student review: made self-contained): the MSB can change at most once per
-- clock, so a large I produces a sampled pattern that LOOKS like a slower,
-- edge-jittered square wave of apparent frequency
--
--     f_apparent = (2**40 - I) * f_clk / 2**40.
--
-- Worked example: the default 30 m carrier (10.14 MHz; "30 m" is the ham
-- band name, ~10 MHz, docs/spec.md section 9) has I > 2**39, so the pin
-- shows an apparent ~1.86 MHz jittery pattern (12 - 10.14 MHz) while the
-- real 10.14 MHz content exists as an image that external band filtering
-- is expected to select (plan section 18).  sim/tb_nco.vhd checks [B]
-- validates this folding numerically.  This block deliberately implements
-- only the frozen spec/plan architecture and leaves any harmonic/filtering
-- decision to the RF/integration phases.
--
-- EDGE JITTER: with an arbitrary I the high/low intervals alternate between
-- floor and ceil of half the period, so every edge carries up to +/-1 clock
-- of jitter; the FREQUENCY LAW above is exact in the average.  Receivers
-- average over thousands of cycles per symbol, so this is harmless here.
--
-- RESET
-- -----
-- Synchronous, active high.  On reset the accumulator is cleared, so rf_out
-- is '0' (RF off) -- consistent with plan section 31: a reset during TX must
-- silence the output.  On the board, top.vhd's power-on reset (16 cycles)
-- guarantees a defined start regardless of whether the FPGA honours the
-- declaration-time register init.
--
-- VHDL-93 ONLY (IEEE Std 1076-1993): explicit sensitivity list, no
-- process(all), no VHDL-2008 constructs.  Analyse with --std=93.
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity nco is
  generic (
    -- Phase-accumulator width.  Frozen at 40 bits (docs/spec.md section 8;
    -- plan section 8: "Use a 40-bit accumulator initially").  It is a generic
    -- so testbenches can exercise narrower/wider accumulators, but the
    -- product default and the increment tool both use 40.
    ACCUMULATOR_BITS : positive := 40
  );
  port (
    clk : in std_logic;   -- FPGA clock (nominal 12 MHz onboard oscillator)
    rst : in std_logic;   -- synchronous reset, active high

    -- Phase increment per clock, ACCUMULATOR_BITS wide.  It is a
    -- std_logic_vector (not unsigned) to keep entity ports type-neutral in
    -- this codebase; the architecture casts it with unsigned(...) below
    -- (student review: explain the cast).  rf_out frequency =
    -- increment * clk_hz / 2**ACCUMULATOR_BITS.
    increment : in std_logic_vector(ACCUMULATOR_BITS - 1 downto 0);

    -- 1-bit continuous-phase carrier (MSB of the phase accumulator).
    rf_out : out std_logic
  );
end entity nco;

architecture rtl of nco is

  ----------------------------------------------------------------------------
  -- Phase state
  ----------------------------------------------------------------------------
  -- The accumulator is the only state.  It is cleared so rf_out starts at '0'
  -- (RF off) after configuration, and clears on reset.  (No clock constant is
  -- declared here: the increment is computed off-chip at build time by
  -- tools/calculate_nco.py from the calibrated clock, so the 12 MHz lives in
  -- the tool and the constraint files, not in this datapath -- student
  -- review: an unused NOMINAL_CLOCK_HZ constant was removed.)
  signal phase_acc : unsigned(ACCUMULATOR_BITS - 1 downto 0) := (others => '0');

begin

  ----------------------------------------------------------------------------
  -- Phase accumulator.  One add per clock.  The wrap IS the modulus: in
  -- numeric_std, `phase_acc + unsigned(increment)` produces a result as wide
  -- as the widest operand and assigning it back to the ACCUMULATOR_BITS-wide
  -- target truncates the carry -- that truncation is exactly the mod
  -- 2**ACCUMULATOR_BITS behaviour (student review: "wraps naturally" hid
  -- this).
  ----------------------------------------------------------------------------
  p_accumulate : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        phase_acc <= (others => '0');
      else
        phase_acc <= phase_acc + unsigned(increment);
      end if;
    end if;
  end process p_accumulate;

  ----------------------------------------------------------------------------
  -- 1-bit carrier: high while the unsigned phase is in its top half
  -- [2**(ACCUMULATOR_BITS-1), 2**ACCUMULATOR_BITS) -- a half-range split of
  -- the UNSIGNED value (student review: the old "MSB is the sign" wording
  -- suggested two's complement, which this is not), giving a continuous-
  -- phase square wave.
  ----------------------------------------------------------------------------
  rf_out <= phase_acc(ACCUMULATOR_BITS - 1);

end architecture rtl;
